export interface Chant {
  slug: string;
  title: string;
  category: string;
  lyrics: string[];
  author?: string;
}

export const chantDatabase: Record<string, Chant> = {
  "kebanggaan-di-hatiku": {
    slug: "kebanggaan-di-hatiku",
    title: "Kebanggaan di Hatiku",
    category: "ANTHEM",
    author: "Bobotoh",
    lyrics: [
      "Kami di sini slalu bersamamu",
      "Bangga mengawal kau kebanggaanku",
      "Tak kenal lelah dan jangan menyerah",
      "Di sini kamu slalu bersamamu",
      "",
      "🔷 Reff:",
      "Ayolah Maung Bandungku",
      "Kami slalu ada untukmu",
      "",
      "Ayolah Maung Bandungku",
      "Kami berjuang bersamamu",
      "",
      "Kami percaya kamu",
      "Kami bangga padamu",
      "Engkaulah kebanggaan di hatiku",
    ],
  },
  "we-will-stay-behind-you": {
    slug: "we-will-stay-behind-you",
    title: "We Will Stay Behind You",
    category: "MATCHDAY",
    author: "Kuburan Band",
    lyrics: [
      "ooo....ooo...oooo..oooo",
      "",
      "Disini ku dapat tegak berdiri",
      "Satukan hati tuk bela kau Persibku",
      "Darah doaku curahkan untukmu",
      "Tuk jadi juara di Indonesia",
      "",
      "🔷 Reff:",
      "Satu biru",
      "Satu hati",
      "Satu bendera kita mendukungmu",
      "",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "ooo.. ooo..",
      "",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "Terus kau bertarung",
      "We are stay behind you",
      "Kau takkan kalah pantang menyerah",
      "Bobotoh mendukungmu",
      "Kau takkan kalah, pantang menyerah",
      "We are stay behind you..",
    ],
  },
  "kami-biru": {
    slug: "kami-biru",
    title: "Kami Biru",
    category: "MATCHDAY",
    author: "Yannahead",
    lyrics: [
      "Kami tetap di sini",
      "Apapun yang kan terjadi",
      "Persib selalu di hati",
      "Persib jiwa raga kami",
      "",
      "🔷 Reff:",
      "Kemenanganmu...kekalahanmu",
      "Tak akan merubah warna kami",
      "",
      "Biru di hatiku biru di jiwaku",
      "Biru di hatiku kami mendukungmu",
      "",
      "Apapun yang terjadi",
      "Semangat kami tak akan mati",
      "Raihlah kemenanganmu",
      "Doa kami bersama mu",
    ],
  },
  "633": {
    slug: "633",
    title: "#633",
    category: "MATCHDAY",
    author: "Standing Terrace",
    lyrics: [
      "we're come from flowers city",
      "we gathers in this city",
      "we born for persib bandung",
      "until we die",
      "",
      "we only support this club",
      "cause this is bandung pride",
      "we didnt have any leader",
      "lets have a drink together",
      "",
      "we dont care people saying",
      "cause we all have anything",
      "as one as bobotoh",
      "our friendship till we die",
      "",
      "never leaves our mates behind",
      "always unite",
      "we're never be devided",
      "cause we're always together",
      "",
      "we all hate nazi scum",
      "our trainers on their face",
      "whenever we are going",
      "always ready to fighting",
      "",
      "🔷 Reff:",
      "our name can be lost",
      "but our soul and pride still alive",
    ],
  },
  "persib-till-i-die": {
    slug: "persib-till-i-die",
    title: "Persib Till I Die",
    category: "MATCHDAY",
    author: "Hooligan Rastaman",
    lyrics: [
     "Persib till I die...",
"Ohh, Persib till I die...",
"I know I am, I'm sure I am",
"Ohh, Persib till I die!!!",
    ],
  },
  "dan-bandung": {
    slug: "dan-bandung",
    title: "Dan Bandung",
    category: "ANTHEM",
    author: "Pidi Baiq",
    lyrics: [
      "Dan Bandung, bagiku bukan cuma",
      "Urusan wilayah belaka",
      "Lebih jauh dari itu, melibatkan perasaan",
      "Yang bersamaku ketika sunyi",
      "",
      "Mungkin saja ada tempat yang lainnya",
      "Ketika ku berada di sana",
      "Akan tetapi perasaanku sepenuhnya ada di Bandung",
      "Yang bersamaku ketika Rindu",
      "",
    ],
  },
  "persib-win-away": {
    slug: "persib-win-away",
    title: "Persib Win Away",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "Jingle Bells, Jingle Bells",
      "Jingle all the way",
      "Oh what fun it is to see",
      "Persib win away.",
    ],
  },
  "chant-for-federico-barba": {
    slug: "chant-for-federico-barba",
    title: "Chant for Federico Barba",
    category: "PLAYER",
    author: "Bobotoh",
    lyrics: [
      "lalalala la, lalalala la",
      "lalalala lalala lalalala",
      "federico barba, from italia",
      "defender persib bandung",
    ],
  },
  "bertandang": {
    slug: "bertandang",
    title: "Bertandang",
    category: "MATCHDAY",
    author: "DT09",
    lyrics: [
      "Saat tiba waktu yang dinanti",
      "Berdebar hati ini",
      "Hutan lautan udara kita kan lalui",
      "Demi membela sebuah harga diri",
      "",
      "Selalu berteriak meluapkan gairah",
      "Berdiri dan terus bernyanyi",
      "Selalu berseriak meluapkan gairah",
      "Berdiri dan terus bernyanyi",
      "",
      "Saat tiba waktu yang dinanti",
      "Berdebar hati ini",
      "Hutan laut dan udara kita kan lalui",
      "Demi membela semua harga diri",
      "",
      "Selalu berteriak meluapkan gairah",
      "Berdiri dan terus bernyanyi",
      "Selalu berteriak meluapkan gairah",
      "Berdiri dan terus bernyanyi",
    ],
  },
  "kebanggaan-bandung": {
    slug: "kebanggaan-bandung",
    title: "Kebanggaan Bandung",
    category: "MATCHDAY",
    author: "DT09",
    lyrics: [
      "Terima kasih tuhan",
      "Bandung tempat kelahiranku",
      "Punya tim kebanggaan persib bandung",
      "Dengan sejarah yang melambung",
      "",
      "Pangeran biru maung bandung",
      "Bangga teriak julukanmu ",
      "Pangeran biru persib bandung ",
      "Tim kebanggaan kota bandung",
      "",
      "Tim kebanggaan kota bandung",
      "Pangeran biru maung bandung",
      "Bangga teriak julukanmu ",
      "Pangeran biru persib bandung ",
      "",
      "Tim kebanggaan kota bandung",
      "Tim kebanggaan kota bandung",
      "Tim kebanggaan kota bandung ",
      "Tim kebanggaan kota bandung",
    ],
  },
  "persib-takan-sendiri": {
    slug: "persib-takan-sendiri",
    title: "Persib Takan Sendiri",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "kudatang kembali",
      "dengan kebanggaan",
      "jangan pernah hentikan kami",
      "persib takan sendiri",
      "",
      "ooooo PER ooooo SIB",
      "oo oo oo oo PERSIB TAKAN SENDIRI",
    ],
  },
  "persib-taklukan-lawan": {
    slug: "persib-taklukan-lawan",
    title: "Persib Taklukan Lawan",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "persib taklukan lawan",
      "persib taklukan lawan",
      "persib taklukan lawan",
      "persib taklukan lawan",
      "",
      "ooo ooo ooo",
      "ooo ooo ooo",
      "ooo ooo ooo",
      "ooo ooo ooooo",
    ],
  },
  "oh-when-the-blues": {
    slug: "oh-when-the-blues",
    title: "Oh When The Blues",
    category: "MATCHDAY",
    author: "sunday eleven",
    lyrics: [
     "Oh when the Blues go marching in!",
"Oh when the Blues go marching in!",
"I wanna be in that number!",
"Oh when the Blues go marching in!"
    ],
  },
  "persib-bandung-itulah-namamu": {
    slug: "persib-bandung-itulah-namamu",
    title: "Persib Bandung Itulah Namamu",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "Persib bandung itulah namamu",
      "maung bandung itulah julukanmu",
      "ayo persib bantailah lawanmu",
      "kami disini slalu mendukungmu",
      "",
      "Oooo.....ooo...oooo...oo..",
      "",
      "Persib bandung itulah namamu",
      "maung bandung itulah julukanmu",
      "ayo persib bantailah lawanmu",
      "kami disini slalu mendukungmu",
      "",
      "Oooo....ooo..oooo...oo....",
    ],
  },
  "persib-bandung-yang-kutunggu": {
    slug: "persib-bandung-yang-kutunggu",
    title: "Persib Bandung yang Kutunggu",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "Persib Bandung Yang Kutunggu kutunggu",
      "Kunanti Nanti",
      "Telah Lama Kuberdiri Berdiri",
      "Kunanti-nanti",
      "",
      "Bila Persib Menang Lagi, ooii Kugembira",
      "Ku kan Slalu Menunggumu",
      "Sampai Mati",
      "",
      "Persib Bandung Yang Kutunggu kutunggu",
      "Kunanti Nanti",
      "Telah Lama Kuberdiri Berdiri",
      "Kunanti - Nanti",
      "",
      "Bila Persib Menang Lagi,",
      "Wooii Kugembira",
      "Ku'kan Slalu Menunggumu Sampai Mati",
    ],
  },
  "were-coming-back": {
    slug: "were-coming-back",
    title: "We're Coming Back",
    category: "MATCHDAY",
    author: "Bobotoh",
    lyrics: [
      "We're coming back",
      "We're coming back",
      "We're coming back to you",
      "We're never gonna go away again",
      "",
      "Hold on a little longer, try a little harder",
      "'Til we're arm in arm together to the end",
      "",
      "Just remember, out there somewhere",
      "You've got a friend, and you'll never walk alone again",
    ],
  },
};

export const defaultChant: Chant = {
  slug: "default",
  title: "Chant Persib",
  category: "UMUM",
  lyrics: ["Hidup Persib!", "Persib, Persib, Persib!"],
};

export const getAllChants = () => Object.values(chantDatabase);
