export interface Chant {
  slug: string;
  title: string;
  category: string;
  lyrics: string[];
  author?: string;
}

export const chantDatabase: Record<string, Chant> = {
  "kebanggaan-di-hatiku": {
    slug: "kebanggaan-di-hatiku",
    title: "Kebanggaan di Hatiku",
    category: "ANTHEM",
    author: "Bobotoh",
    lyrics: [
      "Kami di sini slalu bersamamu",
      "Bangga mengawal kau kebanggaanku",
      "Tak kenal lelah dan jangan menyerah",
      "Di sini kamu slalu bersamamu",
      "",
      "🔷 Reff:",
      "Ayolah Maung Bandungku",
      "Kami slalu ada untukmu",
      "",
      "Ayolah Maung Bandungku",
      "Kami berjuang bersamamu",
      "",
      "Kami percaya kamu",
      "Kami bangga padamu",
      "Engkaulah kebanggaan di hatiku",
    ],
  },
  "we-will-stay-behind-you": {
    slug: "we-will-stay-behind-you",
    title: "We Will Stay Behind You",
    category: "MATCHDAY",
    author: "Kuburan Band",
    lyrics: [
      "ooo....ooo...oooo..oooo",
      "",
      "Disini ku dapat tegak berdiri",
      "Satukan hati tuk bela kau Persibku",
      "Darah doaku curahkan untukmu",
      "Tuk jadi juara di Indonesia",
      "",
      "🔷 Reff:",
      "Satu biru",
      "Satu hati",
      "Satu bendera kita mendukungmu",
      "",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "ooo.. ooo..",
      "",
      "Persib Maung Bandung",
      "Persib Maung Bandung",
      "Terus kau bertarung",
      "We are stay behind you",
      "Kau takkan kalah pantang menyerah",
      "Bobotoh mendukungmu",
      "Kau takkan kalah, pantang menyerah",
      "We are stay behind you..",
    ],
  },
  "kami-biru": {
    slug: "kami-biru",
    title: "Kami Biru",
    category: "MATCHDAY",
    author: "Yannahead",
    lyrics: [
      "Kami tetap di sini",
      "Apapun yang kan terjadi",
      "Persib selalu di hati",
      "Persib jiwa raga kami",
      "",
      "🔷 Reff:",
      "Kemenanganmu...kekalahanmu",
      "Tak akan merubah warna kami",
      "",
      "Biru di hatiku biru di jiwaku",
      "Biru di hatiku kami mendukungmu",
      "",
      "Apapun yang terjadi",
      "Semangat kami tak akan mati",
      "Raihlah kemenanganmu",
      "Doa kami bersama mu",
    ],
  },
  "633": {
    slug: "633",
    title: "#633",
    category: "MATCHDAY",
    author: "Standing Terrace",
    lyrics: [
      "we're come from flowers city",
      "we gathers in this city",
      "we born for persib bandung",
      "until we die",
      "",
      "we only support this club",
      "cause this is bandung pride",
      "we didnt have any leader",
      "lets have a drink together",
      "",
      "we dont care people saying",
      "cause we all have anything",
      "as one as bobotoh",
      "our friendship till we die",
      "",
      "never leaves our mates behind",
      "always unite",
      "we're never be devided",
      "cause we're always together",
      "",
      "we all hate nazi scum",
      "our trainers on their face",
      "whenever we are going",
      "always ready to fighting",
      "",
      "🔷 Reff:",
      "our name can be lost",
      "but our soul and pride still alive",
    ],
  },
  "persib-till-i-die": {
    slug: "persib-till-i-die",
    title: "Persib Till I Die",
    category: "MATCHDAY",
    author: "Hooligan Rastaman",
    lyrics: [
      "Persib till i die...",
      "I'm Persib till i die...",
      "I know i am sure, i am",
      "Persib till i die !!!",
    ],
  },
};

export const defaultChant: Chant = {
  slug: "default",
  title: "Chant Persib",
  category: "UMUM",
  lyrics: ["Hidup Persib!", "Persib, Persib, Persib!"],
};

export const getAllChants = () => Object.values(chantDatabase);
